version: '3.7'

services:

  db:
    container_name: db_postgres
    env_file:
      - envs/postgres.env
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  jupyter:
    build: .
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
    container_name: jupyter_lab
    depends_on:
      - db
    env_file:
      - envs/jupyter.env
    image: bkeyvani/jupyterlab-mini
    ports:
      - '8888:8888'
    volumes:
      - ./code:/code
